### ISSUE TITLE
Decoder for .F files in AMaViS image

### ISSUE THREAD

**Issue by tyranron** [instrumentisto/docker-mailserver#1]
At the moment I failed to compile `freeze` utility from sources via `alpine` container.
See details [here](https://github.com/gliderlabs/docker-alpine/issues/212).

Requires to be resolved somehow in near future.

**Comment by tyranron** [comment]
Source code of `freeze` must be patched to compile with Alpine's `libc` which is different.

**Comment by fff0x** [comment]
I have also no clue what this macro definition does but I simply removed the lines (19-20) in the header file and it compiled without problems. And for me it seems the binary is still working afterwards.

**Comment by tyranron** [comment]
@mbuelte thank you for giving attention.

I haven't dived into sources yet. Just stopped when it failed to compile. Your tip seems quite reasonable. I'll take a closer look soon.

**Comment by tyranron** [comment]
@mbuelte, yeap. That's it.

It was strange idea to redeclare `putc()`.
Hope, usage of std `putc()` won't break anything =)
