### ISSUE TITLE
OpenDMARC on Alpine

### ISSUE THREAD

**Issue by tyranron** [instrumentisto/docker-mailserver#4]
There is no OpenDMARC package in [Alpine Packages repo](https://pkgs.alpinelinux.org/packages).
Related [issue](http://bugs.alpinelinux.org/issues/6124) is created.

Trying to compile it from [sources](https://sourceforge.net/projects/opendmarc/files) failes with following error:

```
opendmarc_dns.c: In function 'dmarc_dns_get_record':
opendmarc_dns.c:172:18: error: 'NETDB_SUCCESS' undeclared (first use in this function)
     *reply_ptr = NETDB_SUCCESS;
                  ^~~~~~~~~~~~~
opendmarc_dns.c:172:18: note: each undeclared identifier is reported only once for each function it appears in
opendmarc_dns.c:220:50: warning: passing argument 2 of 'opendmarc_policy_library_dns_hook' from incompatible pointer type [-Wincompatible-pointer-types]
                                                  &_res.nsaddr_list);
                                                  ^
In file included from opendmarc_dns.c:15:0:
opendmarc_internal.h:233:6: note: expected 'struct sockaddr_in *' but argument is of type 'struct sockaddr_in (*)[3]'
 void opendmarc_policy_library_dns_hook(int *nscountp, struct sockaddr_in *nsaddr_list);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Where `NETDB_SUCCESS` is declaration of `/usr/include/netdb.h` and is missed on Alpine because Alpine uses [musl libc](http://www.musl-libc.org/) instead of glibc.

So we need either write a patch for OpenDMARC sources or try to play with [glibc Alpine image](https://github.com/frol/docker-alpine-glibc).

**Comment by ghost** [comment]
So, there is no way to build OpenDMARC without using glibc under Alpine?

**Comment by tyranron** [comment]
@indignus seems to be no, unless patch it by yourself.

**Comment by fff0x** [comment]
It seems there are only some *NETDB_* defines missing, in comparison with the glibc `netdb.h`. Here is a patch that will allow to compile opendmarc with musl libc, if applied. Afterwards I can run the program without any visual problems.

For whatever reasons, the busybox patch util in Alpine tries to patch the source files in the wrong order, so we have to modify the patch file first:

```
cd opendmarc-1.3.2

sed -i 's/opendmarc_internal.h\t/opendmarc_internal.h.edit\t/' fix_missing_netdb_defines_musl.patch

awk -v n=2 '/opendmarc_internal.h.edit\t/ { if (++count == n) sub(/opendmarc_internal.h.edit\t/, "opendmarc_internal.h\t"); } 1' fix_missing_netdb_defines_musl.patch > tmp && mv -f tmp fix_missing_netdb_defines_musl.patch

patch -p0 < fix_missing_netdb_defines_musl.patch

./configure && make
```

https://gist.github.com/mbuelte/3666df1345828a807526767eacf4f52e

@tyranron does it work for you?

**Comment by tyranron** [comment]
@mbuelte thank you a lot for your help.  
I've [applied your patch](https://github.com/instrumentisto/opendmarc-docker-image/blob/a3911b54964def29f4c14ccab647445313ac1d24/alpine/Dockerfile#L36-L39) in [new OpenDMARC image](https://hub.docker.com/r/instrumentisto/opendmarc). Now it's ready for use.
